#!/bin/bash

# edit to fit config
dir=$HOME/programming/repos/migraine_check
#db=db/migraine.db
db=db/test.db

function usage {
   echo "Syntax: <command> <keyword>"
   echo -e "  keyword := \e[1mm\e[0migraine | \e[1mr\e[0moutine | \e[1mg\e[0mraph"
}

cd $dir

# creating database if it doen't exist
if [ ! -f $db ]; then
    echo "Creating db..."
    sqlite3 -bail $db< dbschema.sql
fi

if [ -z ${1+x} ]; then usage && exit 2; fi

case $1 in
"m" | "migraine")
    exec python3 add_migraine.py $db
    ;;
"r" | "routine")
    exec python3 add_routine.py $db
    ;;
"g" | "graph")
    exec python3 create_graph.py $db
    ;;
*)
    usage && exit 2
    ;;
esac
