#!/bin/bash

# edit to fit config
dir=$HOME/programming/repos/migraine_check
#db=db/migraine.db
db=db/test.db

function usage {
   echo "Syntax: <command> <keyword>"
   echo -e "  keyword := \e[1mm\e[0migraine | \e[1mr\e[0moutine"
}

cd $dir

# creating database if it doen't exist
if [ ! -f $db ]; then
    echo "Creating db..."
    sqlite3 -bail $db<<END009
CREATE TABLE migraine(id INTEGER NOT NULL PRIMARY KEY, start TEXT NOT NULL UNIQUE, end TEXT, duration REAL, intensity INTEGER, comment TEXT);
CREATE TABLE day(date TEXT NOT NULL PRIMARY KEY, sleep_time REAL, comment TEXT);
CREATE TABLE food(name TEXT NOT NULL PRIMARY KEY, comment TEXT);
CREATE TABLE day_food_map(day_id TEXT NOT NULL, food_id TEXT NOT NULL, FOREIGN KEY(day_id) REFERENCES day(date), FOREIGN KEY(food_id) REFERENCES food(name));
END009
fi

if [ -z ${1+x} ]; then usage && exit 2; fi

case $1 in
"m" | "migraine")
    exec python3 add_migraine.py $db
    ;;
"r" | "routine")
    exec python3 add_routine.py $db
    ;;
"g" | "graph")
    exec python3 create_graph.py $db
    ;;
*)
    usage && exit 2
    ;;
esac

#if [ $1 = "m" ] || [ $1 = "migraine" ]; then
#    exec python3 add_migraine.py $db
#
#elif [ $1 = "r" ] || [ $1 = "routine" ]; then
#    exec python3 add_routine.py $db
#
#else
#    usage && exit 2
#fi
